base_url = "/"

title = "Butternaan's Jugaad Blog"
description = "Abhigyan Trips' random thoughts, rants and snippets, all in one place."

default_language = "en"
generate_feed = true
compile_sass = true

highlight_code = true
highlight_theme = "gruvbox-dark" 

build_search_index = false

taxonomies = [
           {name = "tags"},
           {name = "categories"},
]

[extra]

author = "Abhigyan"

show_author = false
show_categories = true
show_tags = true

show_menu_items = 3

main_menu = [
    {url="https://butternaan.xyz/about", name="About", external=true},
    {url="https://butternaan.xyz/projects", name="Projects", external=true},
    {url="https://butternaan.xyz/contact", name="Contact", external=true},
]